#!/usr/bin/env bash
# Ensure Microsoft ONNX Runtime *GPU* build is present for Linux desktop.
#
# Outputs under .onnxruntime-gpu/ (gitignored):
#   lib/libonnxruntime.so
#   lib/libonnxruntime_providers_cuda.so
#   lib/libonnxruntime_providers_shared.so
#
# Usage:
#   ./scripts/setup_onnxruntime_gpu.sh
#   source scripts/onnxruntime_gpu_env.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ORT_VERSION="${HUJI_ONNXRUNTIME_VERSION:-1.22.0}"
ARCH_IN="${1:-$(uname -m)}"
case "$ARCH_IN" in
  x86_64|amd64) ORT_ARCH="x64" ;;
  aarch64|arm64) ORT_ARCH="aarch64" ;;
  *)
    echo "Unsupported arch: $ARCH_IN" >&2
    exit 1
    ;;
esac

DEST_DIR="${HUJI_ONNXRUNTIME_GPU_DIR:-$PROJECT_DIR/.onnxruntime-gpu}"
URL="https://github.com/microsoft/onnxruntime/releases/download/v${ORT_VERSION}/onnxruntime-linux-${ORT_ARCH}-gpu-${ORT_VERSION}.tgz"
ENV_FILE="$SCRIPT_DIR/onnxruntime_gpu_env.sh"

mkdir -p "$DEST_DIR"
ARCHIVE="$DEST_DIR/onnxruntime-gpu.tgz"

if [[ ! -f "$DEST_DIR/lib/libonnxruntime.so" && ! -f "$DEST_DIR/lib/libonnxruntime.so.1" ]]; then
  echo "[download] $URL"
  curl -fL --retry 3 --retry-delay 2 "$URL" -o "$ARCHIVE"
  tar -xzf "$ARCHIVE" -C "$DEST_DIR" --strip-components=1
  echo "[ok] extracted to $DEST_DIR"
else
  echo "[ok] already present under $DEST_DIR/lib"
fi

if [[ ! -f "$DEST_DIR/lib/libonnxruntime.so" ]]; then
  LIB="$(find "$DEST_DIR/lib" -name 'libonnxruntime.so.*' -type f | head -1 || true)"
  if [[ -n "$LIB" ]]; then
    ln -sfn "$(basename "$LIB")" "$DEST_DIR/lib/libonnxruntime.so"
  fi
fi

if [[ ! -f "$DEST_DIR/lib/libonnxruntime.so" ]]; then
  echo "libonnxruntime.so not found under $DEST_DIR/lib" >&2
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by setup_onnxruntime_gpu.sh
export HUJI_ONNXRUNTIME_LIB="$DEST_DIR/lib/libonnxruntime.so"
export HUJI_ONNXRUNTIME_GPU_DIR="$DEST_DIR"
export LD_LIBRARY_PATH="$DEST_DIR/lib:\${LD_LIBRARY_PATH:-}"
EOF

echo "[ok] GPU ORT at $DEST_DIR/lib/libonnxruntime.so"
echo "     source $ENV_FILE"
