// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class ProfileNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 1280
    let windowHeight: Int = 800

    // MARK: - Window Title
    let windowTitle: String = "弧迹"

    // MARK: - Animation control
    let withAnimation: Bool = false

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_profile.png"
    let imageWidth: Int = 1280
    let imageHeight: Int = 800
}
